export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const NEW_TRANSACTION_START = 'NEW_TRANSACTION_START';
export const NEW_TRANSACTION_SUCCESS = 'NEW_TRANSACTION_SUCCESS';
export const NEW_TRANSACTION_FAIL = 'NEW_TRANSACTION_FAIL';
export const NEW_TRANSACTION_INIT = 'NEW_TRANSACTION_INIT';

export const EDIT_TRANSACTION_START = 'EDIT_TRANSACTION_START';
export const EDIT_TRANSACTION_SUCCESS = 'EDIT_TRANSACTION_SUCCESS';
export const EDIT_TRANSACTION_FAIL = 'EDIT_TRANSACTION_FAIL';
export const EDIT_TRANSACTION_INIT = 'EDIT_TRANSACTION_INIT';

export const DELETE_TRANSACTION_START = 'DELETE_TRANSACTION_START';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAIL = 'DELETE_TRANSACTION_FAIL';
export const DELETE_TRANSACTION_INIT = 'DELETE_TRANSACTION_INIT';

export const FETCH_TRANSACTIONS_REQUEST = 'FETCH_TRANSACTIONS_REQUEST';
export const FETCH_TRANSACTIONS_START = 'FETCH_TRANSACTIONS_START';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAIL = 'FETCH_TRANSACTIONS_FAIL';

// projects
export const NEW_PROJECT_START = 'NEW_PROJECT_START';
export const NEW_PROJECT_SUCCESS = 'NEW_PROJECT_SUCCESS';
export const NEW_PROJECT_FAIL = 'NEW_PROJECT_FAIL';
export const NEW_PROJECT_INIT = 'NEW_PROJECT_INIT';

export const EDIT_PROJECT_START = 'EDIT_PROJECT_START';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';
export const EDIT_PROJECT_FAIL = 'EDIT_PROJECT_FAIL';
export const EDIT_PROJECT_INIT = 'EDIT_PROJECT_INIT';

export const DELETE_PROJECT_START = 'DELETE_PROJECT_START';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';
export const DELETE_PROJECT_INIT = 'DELETE_PROJECT_INIT';

export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL';

// Date Range
export const DATE_START = 'DATE_START';
export const DATE_END = 'DATE_END';
// Preset Date Range
export const DATE_LAST_7_DAYS = 'DATE_LAST_7_DAYS';
export const DATE_LAST_14_DAYS = 'DATE_LAST_14_DAYS';
export const DATE_LAST_1_MONTH = 'DATE_LAST_1_MONTH';
export const DATE_LAST_3_MONTH = 'DATE_LAST_3_MONTH';
export const DATE_LAST_6_MONTH = 'DATE_LAST_6_MONTH';
export const DATE_LAST_1_YEAR = 'DATE_LAST_1_YEAR';
export const DATE_ALL_TIME = 'DATE_ALL_TIME';
