export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

/** VEHICLE */
export const NEW_VEHICLE_START = 'NEW_VEHICLE_START';
export const NEW_VEHICLE_SUCCESS = 'NEW_VEHICLE_SUCCESS';
export const NEW_VEHICLE_FAIL = 'NEW_VEHICLE_FAIL';
export const NEW_VEHICLE_INIT = 'NEW_VEHICLE_INIT';

export const EDIT_VEHICLE_START = 'EDIT_VEHICLE_START';
export const EDIT_VEHICLE_SUCCESS = 'EDIT_VEHICLE_SUCCESS';
export const EDIT_VEHICLE_FAIL = 'EDIT_VEHICLE_FAIL';
export const EDIT_VEHICLE_INIT = 'EDIT_VEHICLE_INIT';

export const DELETE_VEHICLE_START = 'DELETE_VEHICLE_START';
export const DELETE_VEHICLE_SUCCESS = 'DELETE_VEHICLE_SUCCESS';
export const DELETE_VEHICLE_FAIL = 'DELETE_VEHICLE_FAIL';
export const DELETE_VEHICLE_INIT = 'DELETE_VEHICLE_INIT';

export const FETCH_VEHICLE_REQUEST = 'FETCH_VEHICLE_REQUEST';
export const FETCH_VEHICLE_START = 'FETCH_VEHICLE_START';
export const FETCH_VEHICLE_SUCCESS = 'FETCH_VEHICLE_SUCCESS';
export const FETCH_VEHICLE_FAIL = 'FETCH_VEHICLE_FAIL';

export const FETCH_VEHICLES_REQUEST = 'FETCH_VEHICLES_REQUEST';
export const FETCH_VEHICLES_START = 'FETCH_VEHICLES_START';
export const FETCH_VEHICLES_SUCCESS = 'FETCH_VEHICLES_SUCCESS';
export const FETCH_VEHICLES_FAIL = 'FETCH_VEHICLES_FAIL';

/** PRODUCT */
export const NEW_PRODUCT_START = 'NEW_PRODUCT_START';
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS';
export const NEW_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL';
export const NEW_PRODUCT_INIT = 'NEW_PRODUCT_INIT';

export const EDIT_PRODUCT_START = 'EDIT_PRODUCT_START';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_FAIL';
export const EDIT_PRODUCT_INIT = 'EDIT_PRODUCT_INIT';

export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_INIT = 'DELETE_PRODUCT_INIT';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_FAIL';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

/** MAINTENANCE */
export const NEW_MAINTENANCE_START = 'NEW_MAINTENANCE_START';
export const NEW_MAINTENANCE_SUCCESS = 'NEW_MAINTENANCE_SUCCESS';
export const NEW_MAINTENANCE_FAIL = 'NEW_MAINTENANCE_FAIL';
export const NEW_MAINTENANCE_INIT = 'NEW_MAINTENANCE_INIT';

export const EDIT_MAINTENANCE_START = 'EDIT_MAINTENANCE_START';
export const EDIT_MAINTENANCE_SUCCESS = 'EDIT_MAINTENANCE_SUCCESS';
export const EDIT_MAINTENANCE_FAIL = 'EDIT_MAINTENANCE_FAIL';
export const EDIT_MAINTENANCE_INIT = 'EDIT_MAINTENANCE_INIT';

export const DELETE_MAINTENANCE_START = 'DELETE_MAINTENANCE_START';
export const DELETE_MAINTENANCE_SUCCESS = 'DELETE_MAINTENANCE_SUCCESS';
export const DELETE_MAINTENANCE_FAIL = 'DELETE_MAINTENANCE_FAIL';
export const DELETE_MAINTENANCE_INIT = 'DELETE_MAINTENANCE_INIT';

export const FETCH_MAINTENANCE_REQUEST = 'FETCH_MAINTENANCE_REQUEST';
export const FETCH_MAINTENANCE_START = 'FETCH_MAINTENANCE_START';
export const FETCH_MAINTENANCE_SUCCESS = 'FETCH_MAINTENANCE_SUCCESS';
export const FETCH_MAINTENANCE_FAIL = 'FETCH_MAINTENANCE_FAIL';

export const FETCH_MAINTENANCES_REQUEST = 'FETCH_MAINTENANCES_REQUEST';
export const FETCH_MAINTENANCES_START = 'FETCH_MAINTENANCES_START';
export const FETCH_MAINTENANCES_SUCCESS = 'FETCH_MAINTENANCES_SUCCESS';
export const FETCH_MAINTENANCES_FAIL = 'FETCH_MAINTENANCES_FAIL';


/** SERVICE */
export const NEW_SERVICE_START = 'NEW_SERVICE_START';
export const NEW_SERVICE_SUCCESS = 'NEW_SERVICE_SUCCESS';
export const NEW_SERVICE_FAIL = 'NEW_SERVICE_FAIL';
export const NEW_SERVICE_INIT = 'NEW_SERVICE_INIT';

export const EDIT_SERVICE_START = 'EDIT_SERVICE_START';
export const EDIT_SERVICE_SUCCESS = 'EDIT_SERVICE_SUCCESS';
export const EDIT_SERVICE_FAIL = 'EDIT_SERVICE_FAIL';
export const EDIT_SERVICE_INIT = 'EDIT_SERVICE_INIT';

export const DELETE_SERVICE_START = 'DELETE_SERVICE_START';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAIL = 'DELETE_SERVICE_FAIL';
export const DELETE_SERVICE_INIT = 'DELETE_SERVICE_INIT';

export const FETCH_SERVICE_REQUEST = 'FETCH_SERVICE_REQUEST';
export const FETCH_SERVICE_START = 'FETCH_SERVICE_START';
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS';
export const FETCH_SERVICE_FAIL = 'FETCH_SERVICE_FAIL';

export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_START = 'FETCH_SERVICES_START';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAIL = 'FETCH_SERVICES_FAIL';

